XML_PATH = "data/xml/"
DOWNLOAD_PATH = "data/pdf/"
XSL_PATH = "data/xsl/"
IMAGE_PATH = "data/images/"

GMAIL_SMTP_USER = ENV["GMAIL_SMTP_USER"]
GMAIL_SMTP_PASSWORD = ENV["GMAIL_SMTP_PASSWORD"]
GMAIL_TEST_RECIPIENT = ENV["GMAIL_TEST_RECIPIENT"]
